name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 16 ]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          ./gradlew build allTests

      - if: success() || failure()
        name: Generate Test Reports
        run: |
          ./gradlew genReport koverXmlReport koverHtmlReport testAggregate
          zip -r build/reports/kover/html.zip build/reports/kover/html
          zip -r build/reports/tests.zip build/reports/tests

      #      - name: Test Report
      #        uses: dorny/test-reporter@v1
      #        if: success() || failure()
      #        with:
      #          name: Test Report
      #          path: build/test-results/**/*.xml
      #          reporter: java-junit

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: Test Report
          path: build/reports/tests

      - name: Upload Kover Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: Kover Report
          path: build/reports/kover/html.zip

      - name: Upload Coverage Report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          files: build/reports/kover/report.xml
