name: Delete Branch on Closed Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: ${{ github.actor == 'shakelang-bot' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete branch
        run: |
          # Extract branch name from the ref
          branch_name=${{ github.event.pull_request.head.ref }}

          # Delete the branch
          git push origin --delete $branch_name
